import "./globals.css";
import PageTransition from "@components/PageTransition";

// Font
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rahul A B || Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <meta name="google-site-verification" content="8MYXOZEXPfoaSBLtN0yG0mDX4C22PLt0P4Onx8kqdEE" />
            <body className={inter.className}>
                <PageTransition>{children}</PageTransition>
            </body>
        </html>
    );
}
